#ifndef POSTGRES_EXT_PREDICATEENUM_H
#define POSTGRES_EXT_PREDICATEENUM_H

enum class Predicate { DISJOINT, MEET, OVERLAP, COVERS, CONTAINS, EQUAL, INSIDE, COVEREDBY };

#endif //POSTGRES_EXT_PREDICATEENUM_H
